DROP TABLE IF EXISTS Detalii_Alte_Studii;
DROP TABLE IF EXISTS EXAMEN;
DROP TABLE IF EXISTS MEDIE;
DROP TABLE IF EXISTS NOTE;
DROP TABLE IF EXISTS ORAR;
DROP TABLE IF EXISTS PREFERINTE;
DROP TABLE IF EXISTS SALI;
DROP TABLE IF EXISTS STUDENT;
DROP TABLE IF EXISTS STUDENT_ORAR;

