DROP TABLE IF EXISTS EXAMEN;
DROP TABLE IF EXISTS MEDIE;
DROP TABLE IF EXISTS NOTE;
DROP TABLE IF EXISTS ORAR;
DROP TABLE IF EXISTS SALI;
DROP TABLE IF EXISTS STUDII;
DROP TABLE IF EXISTS STUDENTI;
DROP TABLE IF EXISTS STUDENTI_ORAR;