DROP TABLE IF EXISTS Examen;
DROP TABLE IF EXISTS Note;
DROP TABLE IF EXISTS Orar;
DROP TABLE IF EXISTS Sali;
DROP TABLE IF EXISTS Studii;
DROP TABLE IF EXISTS "User";
DROP TABLE IF EXISTS user_orar;
