CREATE TABLE CANDIDAT (
  CNP       varchar(13) NOT NULL, 
  TELEFON   varchar(16) NOT NULL, 
  NUME      varchar(255) NOT NULL, 
  PRENUME   varchar(255) NOT NULL, 
  USEREMAIL varchar(255) NOT NULL, 
  PRIMARY KEY (CNP), 
  FOREIGN KEY(USEREMAIL) REFERENCES USER(EMAIL)
  );

CREATE TABLE EXAMEN (
  ID         varchar(10) NOT NULL, 
  NR_PROBA   integer(10) NOT NULL, 
  START_DATE timestamp NOT NULL, 
  END_DATE   timestamp NOT NULL, 
  TIP        varchar(255) NOT NULL, 
  PRIMARY KEY (ID)
  );

CREATE TABLE FORM (
  FORMULAR        text NOT NULL, 
  STATUS      integer(4) NOT NULL, 
  CANDIDATCNP varchar(13) NOT NULL, 
  FOREIGN KEY(CANDIDATCNP) REFERENCES CANDIDAT(CNP)
  );

CREATE TABLE MEDIE (
  VALOARE     numeric(2, 0) NOT NULL, 
  CANDIDATCNP varchar(13) NOT NULL, 
  FOREIGN KEY(CANDIDATCNP) REFERENCES CANDIDAT(CNP)
  );

CREATE TABLE NOTE (
  VALOARE     numeric(2, 0) NOT NULL, 
  CANDIDATCNP varchar(13) NOT NULL, 
  EXAMENID    varchar(10) NOT NULL, 
  FOREIGN KEY(EXAMENID) REFERENCES EXAMEN(ID), 
  FOREIGN KEY(CANDIDATCNP) REFERENCES CANDIDAT(CNP)
  );

CREATE TABLE NOTIFICARI (
  TEXT      varchar(255) NOT NULL, 
  SEEN      integer(2) NOT NULL, 
  USEREMAIL varchar(255) NOT NULL, 
  FOREIGN KEY(USEREMAIL) REFERENCES USER(EMAIL)
  );
  
CREATE TABLE PROFESORI (
  NUME                varchar(255) NOT NULL, 
  PRENUME             varchar(255) NOT NULL, 
  PCNP                varchar(13) NOT NULL,
  PRIMARY KEY (PCNP)
  );

CREATE TABLE SALI (
  ID      varchar(5) NOT NULL, 
  ETAJ VARCAHR(10) NOT NULL,
  LOCURI  integer(3) NOT NULL, 
  PRIMARY KEY (ID)
  );


CREATE TABLE USER (
  ROL   varchar(255) NOT NULL, 
  EMAIL  varchar(255) PRIMARY KEY, 
  PAROLA varchar(255) NOT NULL, 
  TOKEN  varchar(255) NOT NULL
  );


CREATE UNIQUE INDEX CANDIDAT_CNP 
  ON CANDIDAT (CNP);
CREATE UNIQUE INDEX EXAMEN_ID 
  ON EXAMEN (ID);
CREATE UNIQUE INDEX PROFESORI_PCNP 
  ON PROFESORI (PCNP);
CREATE UNIQUE INDEX SALI_ID 
  ON SALI (ID);
CREATE UNIQUE INDEX USER_EMAIL 
  ON USER (EMAIL);

