INSERT INTO SALI (`ID`,`ETAJ`,`LOCURI`) VALUES ('C2','P',30);
INSERT INTO SALI (`ID`,`ETAJ`,`LOCURI`) VALUES ('C210','P',4);
INSERT INTO SALI (`ID`,`ETAJ`,`LOCURI`) VALUES ('C309','1',45);
INSERT INTO SALI (`ID`,`ETAJ`,`LOCURI`) VALUES ('C3','2',48);
INSERT INTO SALI (`ID`,`ETAJ`,`LOCURI`) VALUES ('C1','-1',15);
