INSERT INTO `SALI` (`ID`,`LOCATIE`,`LOCURI`) VALUES (1,"C1",30);
INSERT INTO `SALI` (`ID`,`LOCATIE`,`LOCURI`) VALUES (2,"C208",4);
INSERT INTO `SALI` (`ID`,`LOCATIE`,`LOCURI`) VALUES (3,"C4",45);
INSERT INTO `SALI` (`ID`,`LOCATIE`,`LOCURI`) VALUES (4,"C3",48);
INSERT INTO `SALI` (`ID`,`LOCATIE`,`LOCURI`) VALUES (5,"C1",15);
