INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','Aenean@elit.ca','metus','egestas nunc sed');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','felis.Donec@semper.co.uk','feugiat','Cum sociis');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','luctus@nisiCumsociis.net','eu','quis');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','turpis.egestas.Aliquam@dictum.edu','odio','eget');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','orci.consectetuer.euismod@Aeneangravida.com','tortor,','porttitor vulputate, posuere');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','eu.tellus@Proinsed.com','eu','porttitor');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','ad.litora.torquent@Namporttitorscelerisque.ca','mi','luctus felis purus');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','velit.Aliquam.nisl@nisiCumsociis.edu','auctor,','nec');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','malesuada.fames@necmauris.edu','Curabitur','purus. Maecenas');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','sed.pede.Cum@congueturpis.co.uk','et','enim. Suspendisse');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','pharetra.sed@fringillamilacinia.net','felis','Ut');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','Aliquam.gravida.mauris@nonfeugiatnec.co.uk','purus,','erat nonummy');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','eros@Pellentesquetincidunt.org','ut,','lorem fringilla');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','eget@semNullainterdum.net','et','et malesuada');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','penatibus.et@aliquetmolestie.com','posuere','quis accumsan');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','vel@rhoncusDonec.net','libero','diam');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','Cras.eget@bibendumullamcorper.org','vulputate,','ligula consectetuer rhoncus.');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','tristique.pellentesque.tellus@antelectus.edu','et','Nunc lectus pede,');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','senectus.et.netus@atfringilla.co.uk','sem','magna');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','at.velit.Cras@Fusce.ca','vestibulum.','Aenean eget magna.');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','Nullam.ut.nisi@pedenonummyut.edu','id','libero');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','non@dictummi.edu','Mauris','id sapien.');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','hendrerit@risus.org','dolor.','velit dui,');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','facilisis@ridiculusmusProin.edu','faucibus','lobortis quam a');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','taciti.sociosqu.ad@Integertincidunt.net','nisl.','purus sapien,');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','vestibulum@penatibus.co.uk','Duis','mollis');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','lorem.eu.metus@pedePraesenteu.edu','a,','congue, elit sed');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','erat.volutpat@ultricessitamet.net','amet,','id risus quis');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','justo.Proin@Quisque.org','scelerisque','Quisque');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','ac.tellus.Suspendisse@aarcuSed.edu','lectus','egestas nunc sed');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','elit.pellentesque.a@interdumligulaeu.edu','quis','Aliquam');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','Nunc@volutpatnuncsit.co.uk','Etiam','odio sagittis');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','ridiculus.mus.Proin@Quisquenonummyipsum.ca','Nunc','non,');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','Vivamus.nisi@placerataugue.net','Maecenas','eget metus');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','sit@ultriciessemmagna.net','id','velit justo nec');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','nisi.magna.sed@scelerisque.ca','amet','scelerisque neque. Nullam');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','vitae.risus@sociis.org','facilisis','ligula.');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','Etiam.gravida@sollicitudinadipiscingligula.com','sed','consequat enim diam');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','posuere@nequevenenatislacus.ca','aliquet','sit amet, consectetuer');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','elit@eu.edu','ipsum.','odio, auctor vitae,');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','lorem@miAliquamgravida.net','urna','Phasellus');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','ullamcorper.Duis.cursus@nonsollicitudina.net','et,','augue porttitor interdum.');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','sagittis.lobortis.mauris@portaelita.co.uk','Curae;','inceptos hymenaeos.');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','vel.turpis.Aliquam@Morbinon.co.uk','iaculis','Aliquam gravida');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','arcu@purus.co.uk','neque','mauris, aliquam');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','Donec.felis@Sedeunibh.edu','semper','ligula.');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','ut.eros@loremvitaeodio.net','lorem,','Etiam');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','Nunc.sollicitudin@nullaCras.com','lorem','elit');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','sagittis@Maecenasornareegestas.net','Cras','feugiat');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','facilisis.lorem@Nullafacilisis.edu','ac','molestie');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','montes.nascetur@atsemmolestie.edu','Nam','cursus. Integer mollis.');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','turpis.egestas@aliquetlobortis.org','commodo','laoreet');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','Cum.sociis.natoque@gravida.ca','lobortis','varius et, euismod');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','quis.diam@elementumsem.ca','libero','montes, nascetur ridiculus');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','nec.malesuada@inceptoshymenaeosMauris.edu','est','quam vel sapien');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','Sed.congue@Nullamsuscipit.net','Vivamus','enim nisl');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','malesuada.Integer@dolortempusnon.edu','ac','lobortis risus.');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','dictum@lectusasollicitudin.com','dictum','dolor vitae');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','sit.amet@in.org','elementum','pellentesque, tellus sem');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','Nunc.laoreet.lectus@nonmagnaNam.co.uk','at,','lorem');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','eget@hymenaeosMaurisut.net','Aenean','enim.');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','Curabitur@sedest.net','Nam','in');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','vitae@egestas.co.uk','Sed','Cum sociis');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','Quisque@vitaemauris.edu','mauris','dictum sapien.');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','eu.odio.tristique@sitamet.ca','lobortis,','cursus purus.');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','Aliquam@vulputatelacusCras.ca','sit','in aliquet lobortis,');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','Nunc@eudolor.net','sapien.','mauris.');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','vel.arcu.eu@amet.edu','pede,','cursus purus.');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','massa@nislQuisque.com','Ut','Nunc commodo');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','at.iaculis.quis@nullaInteger.com','nisi','erat semper rutrum.');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','Sed.congue@parturient.org','blandit.','nostra, per inceptos');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','orci.Ut.semper@luctussitamet.org','est','id');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','vel.venenatis@consequatlectus.net','lacus.','ac,');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','nascetur@iaculisaliquet.edu','leo.','per');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','egestas.Fusce.aliquet@elitpedemalesuada.net','condimentum','magna. Praesent interdum');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','vulputate@Nullamvitae.ca','risus,','augue,');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','consectetuer.rhoncus.Nullam@nequevitae.com','sit','euismod et,');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','iaculis.quis@natoquepenatibuset.org','rhoncus.','senectus et netus');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','tempus@Curae.edu','Aenean','lorem ut');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','quam@vulputate.ca','rutrum,','iaculis, lacus');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','Aliquam.fringilla.cursus@loremvitaeodio.edu','vel','a, malesuada id,');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','massa.Vestibulum.accumsan@at.net','mi','sapien. Cras');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','sapien.Aenean@nasceturridiculusmus.co.uk','sem','magna nec quam.');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','tellus.Nunc@pharetra.org','ut','natoque penatibus et');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','enim.non@nonjustoProin.co.uk','amet','consectetuer euismod est');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','posuere@molestiearcuSed.co.uk','amet','eu turpis. Nulla');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','odio.vel@idenim.org','nunc','quis');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','eget.ipsum@parturient.com','mi','elit. Nulla facilisi.');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','libero@dapibus.edu','tortor.','rhoncus');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','non@risusvarius.co.uk','Etiam','facilisis vitae,');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','nisi@idmagnaet.com','Phasellus','Cras interdum. Nunc');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','venenatis.lacus.Etiam@arcuimperdiet.org','dui','varius ultrices,');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','at@metusvitae.org','in','tempus');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','sit.amet@anteVivamus.co.uk','feugiat','lorem');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','risus.at@orcisem.edu','lacinia','Vivamus');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','nulla.Cras@Morbineque.com','vel,','nunc risus');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','nulla.Cras.eu@Fuscefermentumfermentum.edu','auctor','nunc interdum feugiat.');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','ullamcorper.nisl@velarcueu.com','neque.','ligula. Aenean');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','a@consectetueripsum.com','eu','Maecenas');
INSERT INTO USER ('ROL','EMAIL','PAROLA','TOKEN') VALUES ('Elev','Quisque.ac@ultrices.net','fringilla,','velit. Quisque varius.');